// Copyright (c) Jonathan Shook
// SPDX-License-Identifier: Apache-2.0

//! `veks prepare synthesize` — one-command synthetic dataset generation.
//!
//! A thin orchestrator over the *existing* facility, not a parallel
//! implementation:
//!
//! 1. **Generate** base + query vectors with the standard `generate vectors`
//!    (uniform) or `generate from-model` (distribution model) commands.
//! 2. **Bootstrap** the dataset directory + pipeline via
//!    [`crate::prepare::import::run`], passing the `--sized-profiles` spec
//!    straight through.
//! 3. **Run** that pipeline via [`crate::pipeline::run_pipeline`].
//!
//! Query shuffling, per-profile ground truth, dedup/zero scans, and merkle
//! are all produced by `veks run` — none of it is re-implemented here.

use std::path::{Path, PathBuf};

use crate::pipeline::RunArgs;
use crate::prepare::import::{self, ImportArgs};

/// Parsed `prepare synthesize` arguments.
pub(crate) struct SynthesizeArgs {
    pub output: PathBuf,
    pub name: Option<String>,
    pub base_count: String,
    pub query_count: String,
    pub dimension: Option<u32>,
    pub metric: String,
    pub neighbors: u32,
    pub sized_profiles: Option<String>,
    pub model: Option<PathBuf>,
    pub min: f32,
    pub max: f32,
    pub seed: u32,
    pub force: bool,
}

pub(crate) fn run(args: SynthesizeArgs) {
    let name = args.name.clone().unwrap_or_else(|| {
        args.output
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_else(|| "generated-dataset".to_string())
    });

    // A model supplies the dimension; otherwise it's required up front.
    if args.model.is_none() && args.dimension.is_none() {
        eprintln!("Error: --dimension is required (or pass --model)");
        std::process::exit(1);
    }

    if let Err(e) = std::fs::create_dir_all(&args.output) {
        eprintln!("Error: failed to create {}: {}", args.output.display(), e);
        std::process::exit(1);
    }
    let dataset_yaml = args.output.join("dataset.yaml");
    if dataset_yaml.exists() && !args.force {
        eprintln!("Error: {} already exists. Pass --force to overwrite.", dataset_yaml.display());
        std::process::exit(1);
    }

    // ── 1) Generate source vectors via the existing generate commands ──
    // Source originals are underscore-prefixed by convention: the pipeline
    // extracts the canonical facets from them, and `_`-prefixed files are
    // excluded from the publishable set (so `veks check` / publish skip
    // them) while staying on disk for re-runs.
    let base_path = args.output.join("_base.fvec");
    let query_path = args.output.join("_query.fvec");
    generate_one(&args, &base_path, &args.base_count, args.seed, "base");
    generate_one(&args, &query_path, &args.query_count, args.seed.wrapping_add(1), "query");
    for (label, p) in [("base", &base_path), ("query", &query_path)] {
        if !p.exists() {
            eprintln!("Error: {label}-vector generation produced no output at {}", p.display());
            std::process::exit(1);
        }
    }

    // ── 2) Bootstrap the dataset + pipeline (sized profiles passed through) ──
    // Synthetic vectors aren't pre-normalized, so COSINE evaluates the proper
    // cosine kernel; other metrics need no cosine strategy.
    let cosine_mode = if args.metric.eq_ignore_ascii_case("cosine") {
        Some("proper".to_string())
    } else {
        None
    };
    println!("Bootstrapping '{name}' in {}…", args.output.display());
    import::run(ImportArgs { merge: false, fetch: None,
        name: name.clone(),
        output: args.output.clone(),
        base_vectors: Some(base_path),
        query_vectors: Some(query_path),
        self_search: false,
        query_count: 0, // queries are an explicit file, not extracted from base
        metadata: None,
        ground_truth: None,
        ground_truth_distances: None,
        metric: args.metric.clone(),
        neighbors: args.neighbors,
        seed: args.seed,
        description: Some("Synthetic dataset generated by `veks prepare synthesize`".to_string()),
        no_dedup: false,
        no_zero_check: false,
        duplicate_count: None,
        zero_count: None,
        no_filtered: false,
        normalize: false,
        force: args.force,
        base_convert_format: None,
        query_convert_format: None,
        compress_cache: false,
        sized_profiles: args.sized_profiles.clone(),
        base_fraction: 1.0,
        pedantic_dedup: false,
        required_facets: None,
        provided_facets: None,
        round_digits: 2,
        selectivity: 0.0001,
        predicate_count: 10000,
        predicate_strategy: "eq".to_string(),
        classic: false,
        personality: "native".to_string(),
        synthesize_metadata: false,
        synthesis_mode: "simple-int-eq".to_string(),
        synthesis_format: "slab".to_string(),
        metadata_fields: 3,
        metadata_range_min: 0,
        metadata_range_max: 1000,
        predicate_range_min: 0,
        predicate_range_max: 1000,
        verify_knn_sample: 0,
        partition_oracles: false,
        max_partitions: 100,
        on_undersized: "error".to_string(),
        cosine_mode,
    });
    if !dataset_yaml.exists() {
        eprintln!("Error: bootstrap did not produce {}", dataset_yaml.display());
        std::process::exit(1);
    }

    // ── 3) Run the pipeline (GT per profile, dedup/zeros, merkle, …) ──
    println!("Running pipeline…");
    let run_args = RunArgs {
        dataset: Some(dataset_yaml.clone()),
        recursive: false,
        profile: "all".to_string(),
        dry_run: false,
        clean: false,
        clean_last: false,
        reset: false,
        overrides: Vec::new(),
        threads: 0,
        emit_yaml: false,
        resources: None,
        governor: "maximize".to_string(),
        status_interval: 250,
        output: "auto".to_string(),
        provenance: "strict".to_string(),
        explain_staleness: false,
    };
    if crate::pipeline::run_pipeline(run_args).is_err() {
        std::process::exit(1);
    }

    println!("\nDataset ready: {}", args.output.display());
}

/// Generate one fvec file by driving the existing `generate` command — the
/// same fully-instrumented code path the CLI uses. `count` accepts unit
/// suffixes (`1M`, `10k`); the generate command parses them.
fn generate_one(args: &SynthesizeArgs, out: &Path, count: &str, seed: u32, label: &str) {
    let out_s = out.to_string_lossy().into_owned();
    let argv: Vec<String> = if let Some(model) = &args.model {
        vec![
            "generate".into(), "from-model".into(),
            "--model".into(), model.to_string_lossy().into_owned(),
            "--output".into(), out_s,
            "--count".into(), count.to_string(),
            "--seed".into(), seed.to_string(),
        ]
    } else {
        vec![
            "generate".into(), "vectors".into(),
            "--output".into(), out_s,
            "--type".into(), "float[]".into(),
            "--dimension".into(), args.dimension.expect("validated above").to_string(),
            "--count".into(), count.to_string(),
            "--seed".into(), seed.to_string(),
            "--min".into(), args.min.to_string(),
            "--max".into(), args.max.to_string(),
        ]
    };
    println!("Generating {label} vectors…");
    crate::pipeline::cli::run_direct(argv);
}
